#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
source "$ROOT/version.env"
# The engine's build identity, the same three fields the server stamp carries: the release version (from
# version.env), the commit this checkout is at, and the commit's own time. A git-less source tree (a release
# tarball) reports "unknown" rather than failing.
GIT_COMMIT=$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo unknown)
GIT_COMMIT_TIME=$(git -C "$ROOT" show -s --format=%cI HEAD 2>/dev/null || echo unknown)
OUTPUT="$ROOT/Sources/imsg/Version.swift"
PLIST_OUTPUT="$ROOT/Sources/imsg/Resources/Info.plist"
mkdir -p "$(dirname "$OUTPUT")"
mkdir -p "$(dirname "$PLIST_OUTPUT")"
cat > "$OUTPUT" <<SWIFT
// Generated by scripts/generate-version.sh. Do not edit.
enum IMsgVersion {
  static let current = "${MARKETING_VERSION}"
  static let commit = "${GIT_COMMIT}"
  static let builtAt = "${GIT_COMMIT_TIME}"
}
SWIFT

# Generated header consumed by the injected helper (IMsgHelper) so the dylib
# can report the release it was built from; `status` and `launch` compare it
# against the running CLI version to detect a stale injected dylib.
HELPER_HEADER_OUTPUT="$ROOT/Sources/IMsgHelper/BridgeVersion.h"
mkdir -p "$(dirname "$HELPER_HEADER_OUTPUT")"
cat > "$HELPER_HEADER_OUTPUT" <<HEADER
// Generated by scripts/generate-version.sh. Do not edit.
#define IMSG_BRIDGE_HELPER_VERSION "${MARKETING_VERSION}"
HEADER

cat > "$PLIST_OUTPUT" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key>
  <string>com.steipete.imsg</string>
  <key>CFBundleName</key>
  <string>imsg</string>
  <key>CFBundleExecutable</key>
  <string>imsg</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>${MARKETING_VERSION}</string>
  <key>CFBundleVersion</key>
  <string>${MARKETING_VERSION}</string>
  <key>NSAppleEventsUsageDescription</key>
  <string>Send messages via Messages.app.</string>
  <key>NSContactsUsageDescription</key>
  <string>Resolve contact names for Messages conversations.</string>
</dict>
</plist>
PLIST
